export const whatNeedsToBeDone = 'What needs to be done?';
export const getSomeMilk = 'Get some milk.';
export const todoTitle = "todo-title";
export const writeMoreCode = 'Write more code';
export const getYourActTogether = 'Get your act together';
export const all = 'All';
export const enter = 'Enter';
export const body = 'body';
export const link = 'link';